### ISSUE TITLE
CertusTank causes crash when filled by TE Fluid Transposer

### ISSUE THREAD

**Issue by the-ible** [M3gaFr3ak/ExtraCells2#177]
Be warned, this bug is intermittant. 
I am unable to reproduce with exactly the same methods every time. It's the very definition of insanity. Perform the same actions and get different results.

I have been able to produce the bug in single player twice.
Once with Resonant Enderium
Once with Cryothium
The crash logs both times were exactly the same.

ExtraCells-1.7.10-2.2.46b72.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-18.jar
Java Version: 1.7.0_76, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2/20/15 7:00 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at extracells.item.ItemBlockCertusTank.fill(ItemBlockCertusTank.java:141)
        at thermalexpansion.block.machine.TileTransposer.updateContainerFill(TileTransposer.java:374)
        at thermalexpansion.block.machine.TileTransposer.processContainerItem(TileTransposer.java:302)
        at thermalexpansion.block.machine.TileTransposer.func_145845_h(TileTransposer.java:101)
        at net.minecraft.world.World.func_72939_s(World.java:2491)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at extracells.item.ItemBlockCertusTank.fill(ItemBlockCertusTank.java:141)
        at thermalexpansion.block.machine.TileTransposer.updateContainerFill(TileTransposer.java:374)
        at thermalexpansion.block.machine.TileTransposer.processContainerItem(TileTransposer.java:302)
        at thermalexpansion.block.machine.TileTransposer.func_145845_h(TileTransposer.java:101)

-- Block entity being ticked --
Details:
        Name: thermalexpansion.Transposer // thermalexpansion.block.machine.TileTransposer
        Block type: ID #1428 (tile.thermalexpansion.machine // thermalexpansion.block.machine.BlockMachine)
        Block data value: 5 / 0x5 / 0b0101
        Block location: World: (20,72,1365), Chunk: (at 4,4,5 in 1,85; contains blocks 16,0,1360 to 31,255,137
5), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
        Actual block type: ID #1428 (tile.thermalexpansion.machine // thermalexpansion.block.machine.BlockMach
ine)
        Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2491)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

**Comment by DrummerMC** [comment]
Update ec to the newest rv2 Version
